version: '3'

services:
  redis:
    container_name: 'redis'
    image: 'redis:latest'
    ports:
      - '6380:6379'
    

  app:
    container_name: 'app'
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - redis